[package]
name = "enarx-proto"
version = "0.1.0"
authors = ["Will Woods <will@profian.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
tonic = "0.5"
prost = "0.8"
prost-types = "0.8"

[build-dependencies]
tonic-build = "0.5"
